# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  id-token: write
  contents: read

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job:
    environment: default
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ env.ACTIONS_RUNTIME_TOKEN }}
    - shell: bash
      run: |
          echo 0
          echo $ACTIONS_RUNTIME_TOKEN
          echo 1
          echo $ACTIONS_ID_TOKEN_REQUEST_URL
          echo 2
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
    - run: terraform init
    - id: plan
      run: terraform plan
    - id: apply
      run: terraform apply